# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: envoy/extensions/clusters/dynamic_forward_proxy/v3/cluster.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto
from betterproto.grpc.grpclib_server import ServiceBase


@dataclass(eq=False, repr=False)
class ClusterConfig(betterproto.Message):
    """
    Configuration for the dynamic forward proxy cluster. See the
    :ref:`architecture overview <arch_overview_http_dynamic_forward_proxy>` for
    more information. [#extension: envoy.clusters.dynamic_forward_proxy]
    """

    # The DNS cache configuration that the cluster will attach to. Note this
    # configuration must match that of associated :ref:`dynamic forward proxy
    # HTTP filter configuration <envoy_api_field_extensions.filters.http.dynamic_
    # forward_proxy.v3.FilterConfig.dns_cache_config>`.
    dns_cache_config: "___common_dynamic_forward_proxy_v3__.DnsCacheConfig" = (
        betterproto.message_field(1)
    )


from ....common.dynamic_forward_proxy import v3 as ___common_dynamic_forward_proxy_v3__
