# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: envoy/extensions/common/matching/v4alpha/extension_matcher.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto
from betterproto.grpc.grpclib_server import ServiceBase


@dataclass(eq=False, repr=False)
class ExtensionWithMatcher(betterproto.Message):
    """
    Wrapper around an existing extension that provides an associated matcher.
    This allows decorating an existing extension with a matcher, which can be
    used to match against relevant protocol data.
    """

    # The associated matcher.
    matcher: "____config_common_matcher_v4_alpha__.Matcher" = betterproto.message_field(
        1
    )
    # The underlying extension config.
    extension_config: "____config_core_v4_alpha__.TypedExtensionConfig" = (
        betterproto.message_field(2)
    )


from .....config.common.matcher import v4alpha as ____config_common_matcher_v4_alpha__
from .....config.core import v4alpha as ____config_core_v4_alpha__
