# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: envoy/config/filter/http/cors/v2/cors.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto
from betterproto.grpc.grpclib_server import ServiceBase


@dataclass(eq=False, repr=False)
class Cors(betterproto.Message):
    """Cors filter config."""

    pass
