# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: envoy/service/auth/v2alpha/external_auth.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import Dict

import betterproto
from betterproto.grpc.grpclib_server import ServiceBase
import grpclib


class AuthorizationStub(betterproto.ServiceStub):
    async def check(
        self, *, attributes: "AttributeContext" = None
    ) -> "_v2__.CheckResponse":

        request = _v2__.CheckRequest()
        if attributes is not None:
            request.attributes = attributes

        return await self._unary_unary(
            "/envoy.service.auth.v2alpha.Authorization/Check",
            request,
            _v2__.CheckResponse,
        )


class AuthorizationBase(ServiceBase):
    async def check(self, attributes: "AttributeContext") -> "_v2__.CheckResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_check(self, stream: grpclib.server.Stream) -> None:
        request = await stream.recv_message()

        request_kwargs = {
            "attributes": request.attributes,
        }

        response = await self.check(**request_kwargs)
        await stream.send_message(response)

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {
            "/envoy.service.auth.v2alpha.Authorization/Check": grpclib.const.Handler(
                self.__rpc_check,
                grpclib.const.Cardinality.UNARY_UNARY,
                _v2__.CheckRequest,
                _v2__.CheckResponse,
            ),
        }


from .. import v2 as _v2__
