# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: envoy/extensions/watchdog/abort_action/v3alpha/abort_action.proto
# plugin: python-betterproto
from dataclasses import dataclass
from datetime import timedelta

import betterproto
from betterproto.grpc.grpclib_server import ServiceBase


@dataclass(eq=False, repr=False)
class AbortActionConfig(betterproto.Message):
    """
    This is currently only implemented for systems that support kill to send
    signals.
    """

    # How long to wait for the thread to respond to the SIGABRT before killing
    # the process from this action. This is a blocking action.
    wait_duration: timedelta = betterproto.message_field(1)
