# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: envoy/extensions/stat_sinks/wasm/v3/wasm.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto
from betterproto.grpc.grpclib_server import ServiceBase


@dataclass(eq=False, repr=False)
class Wasm(betterproto.Message):
    # General Plugin configuration.
    config: "___wasm_v3__.PluginConfig" = betterproto.message_field(1)


from ....wasm import v3 as ___wasm_v3__
