# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: envoy/config/filter/http/grpc_http1_bridge/v2/config.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto
from betterproto.grpc.grpclib_server import ServiceBase


@dataclass(eq=False, repr=False)
class Config(betterproto.Message):
    """gRPC HTTP/1.1 Bridge filter config."""

    pass
