# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: envoy/extensions/clusters/aggregate/v3/cluster.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto
from betterproto.grpc.grpclib_server import ServiceBase


@dataclass(eq=False, repr=False)
class ClusterConfig(betterproto.Message):
    """
    Configuration for the aggregate cluster. See the :ref:`architecture
    overview <arch_overview_aggregate_cluster>` for more information.
    [#extension: envoy.clusters.aggregate]
    """

    # Load balancing clusters in aggregate cluster. Clusters are prioritized
    # based on the order they appear in this list.
    clusters: List[str] = betterproto.string_field(1)
