# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: envoy/config/retry/omit_host_metadata/v2/omit_host_metadata_config.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto
from betterproto.grpc.grpclib_server import ServiceBase


@dataclass(eq=False, repr=False)
class OmitHostMetadataConfig(betterproto.Message):
    """
    A retry host predicate that can be used to reject a host based on
    predefined metadata match criteria. [#extension:
    envoy.retry_host_predicates.omit_host_metadata]
    """

    # Retry host predicate metadata match criteria. The hosts in the upstream
    # cluster with matching metadata will be omitted while attempting a retry of
    # a failed request. The metadata should be specified under the *envoy.lb*
    # key.
    metadata_match: "____api_v2_core__.Metadata" = betterproto.message_field(1)


from .....api.v2 import core as ____api_v2_core__
