# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: envoy/config/filter/http/lua/v2/lua.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto
from betterproto.grpc.grpclib_server import ServiceBase


@dataclass(eq=False, repr=False)
class Lua(betterproto.Message):
    # The Lua code that Envoy will execute. This can be a very small script that
    # further loads code from disk if desired. Note that if JSON configuration is
    # used, the code must be properly escaped. YAML configuration may be easier
    # to read since YAML supports multi-line strings so complex scripts can be
    # easily expressed inline in the configuration.
    inline_code: str = betterproto.string_field(1)
