# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: envoy/extensions/internal_redirect/allow_listed_routes/v3/allow_listed_routes_config.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto
from betterproto.grpc.grpclib_server import ServiceBase


@dataclass(eq=False, repr=False)
class AllowListedRoutesConfig(betterproto.Message):
    """
    An internal redirect predicate that accepts only explicitly allowed target
    routes. [#extension:
    envoy.internal_redirect_predicates.allow_listed_routes]
    """

    # The list of routes that's allowed as redirect target by this predicate,
    # identified by the route's :ref:`name
    # <envoy_api_field_config.route.v3.Route.route>`. Empty route names are not
    # allowed.
    allowed_route_names: List[str] = betterproto.string_field(1)
