# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: envoy/extensions/filters/http/aws_lambda/v3/aws_lambda.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto
from betterproto.grpc.grpclib_server import ServiceBase


class ConfigInvocationMode(betterproto.Enum):
    SYNCHRONOUS = 0
    ASYNCHRONOUS = 1


@dataclass(eq=False, repr=False)
class Config(betterproto.Message):
    """AWS Lambda filter config"""

    # The ARN of the AWS Lambda to invoke when the filter is engaged Must be in
    # the following format: arn:<partition>:lambda:<region>:<account-
    # number>:function:<function-name>
    arn: str = betterproto.string_field(1)
    # Whether to transform the request (headers and body) to a JSON payload or
    # pass it as is.
    payload_passthrough: bool = betterproto.bool_field(2)
    # Determines the way to invoke the Lambda function.
    invocation_mode: "ConfigInvocationMode" = betterproto.enum_field(3)


@dataclass(eq=False, repr=False)
class PerRouteConfig(betterproto.Message):
    """
    Per-route configuration for AWS Lambda. This can be useful when invoking a
    different Lambda function or a different version of the same Lambda
    depending on the route.
    """

    invoke_config: "Config" = betterproto.message_field(1)
