# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: envoy/extensions/access_loggers/file/v4alpha/file.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto
from betterproto.grpc.grpclib_server import ServiceBase


@dataclass(eq=False, repr=False)
class FileAccessLog(betterproto.Message):
    """
    Custom configuration for an :ref:`AccessLog
    <envoy_api_msg_config.accesslog.v4alpha.AccessLog>` that writes log entries
    directly to a file. Configures the built-in *envoy.access_loggers.file*
    AccessLog. [#next-free-field: 6]
    """

    # A path to a local file to which to write the access log entries.
    path: str = betterproto.string_field(1)
    # Configuration to form access log data and format. If not specified, use
    # :ref:`default format <config_access_log_default_format>`.
    log_format: "____config_core_v4_alpha__.SubstitutionFormatString" = (
        betterproto.message_field(5, group="access_log_format")
    )


from .....config.core import v4alpha as ____config_core_v4_alpha__
