# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: envoy/config/retry/omit_canary_hosts/v2/omit_canary_hosts.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto
from betterproto.grpc.grpclib_server import ServiceBase


@dataclass(eq=False, repr=False)
class OmitCanaryHostsPredicate(betterproto.Message):
    pass
