# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: envoy/extensions/common/matching/v3/extension_matcher.proto
# plugin: python-betterproto
import warnings
from dataclasses import dataclass

import betterproto
from betterproto.grpc.grpclib_server import ServiceBase


@dataclass(eq=False, repr=False)
class ExtensionWithMatcher(betterproto.Message):
    """
    Wrapper around an existing extension that provides an associated matcher.
    This allows decorating an existing extension with a matcher, which can be
    used to match against relevant protocol data.
    """

    # The associated matcher. This is deprecated in favor of xds_matcher.
    matcher: "____config_common_matcher_v3__.Matcher" = betterproto.message_field(1)
    # The associated matcher.
    xds_matcher: "_____xds_type_matcher_v3__.Matcher" = betterproto.message_field(3)
    # The underlying extension config.
    extension_config: "____config_core_v3__.TypedExtensionConfig" = (
        betterproto.message_field(2)
    )

    def __post_init__(self) -> None:
        super().__post_init__()
        if self.matcher:
            warnings.warn(
                "ExtensionWithMatcher.matcher is deprecated", DeprecationWarning
            )


from ......xds.type.matcher import v3 as _____xds_type_matcher_v3__
from .....config.common.matcher import v3 as ____config_common_matcher_v3__
from .....config.core import v3 as ____config_core_v3__
