name: Run python tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        poetry install --no-root
    - name: Compile Protobufs
      run: |
        poetry run python utils/download_protobufs.py
        poetry install
    - name: Test with pytest
      run: |
        poetry run pytest --spec -vvv
