# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: envoy/extensions/formatter/req_without_query/v3/req_without_query.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto
from betterproto.grpc.grpclib_server import ServiceBase


@dataclass(eq=False, repr=False)
class ReqWithoutQuery(betterproto.Message):
    """Configuration for the request without query formatter."""

    pass
